name: miniav_ffi
description: A Dart FFI library for the miniav project, providing bindings to the native miniav C library.
version: 0.4.4
repository: https://github.com/PracticalXR/miniAV/tree/master/miniav_ffi

environment:
  sdk: ^3.9.0-21.0.dev

dependencies:
  ffi: ^2.0.2
  miniav_platform_interface: 0.4.4
  native_toolchain_cmake: ^0.0.6-dev.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  ffigen: ^18.0.0

  #####

ffigen:
  name: miniavFfiBindings
  description: Bindings for miniav.h
  output: "lib/miniav_ffi_bindings.dart"
  headers:
    entry-points:
      - "miniav_c/include/miniav.h"
    include-directives:
      - "miniav_c/include/*.h"
      - "/usr/lib/clang/18/include/stdbool.h"
      - "/usr/lib/clang/18/include/stdint.h"
  preamble: |
    // ignore_for_file: camel_case_types
    // ignore_for_file: prefer_double_quotes
    // ignore_for_file: non_constant_identifier_names
    // ignore_for_file: constant_identifier_names
    // ignore_for_file: prefer_expression_function_bodies
    // ignore_for_file: sort_constructors_first
    // ignore_for_file: unused_element 
  llvm-path:
    - /usr/lib64/libclang.so
  compiler-opts:
    - "-I/usr/lib/clang/18/include/"
  ffi-native:
  silence-enum-warning: true
