name: miniav_web
description: A web implementation of the miniav library.
version: 0.4.4
repository: https://github.com/PracticalXR/miniAV/tree/master/miniav_web

environment:
  sdk: ^3.9.0-21.0.dev

dependencies:
  miniav_platform_interface: 0.4.4
  web: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
