name: miniav_web
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0-21.0.dev

# Add regular dependencies here.
dependencies:
  miniav_platform_interface:
    path: ../miniav_platform_interface
  web: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
