name: miniav
description: A cross-platform capture library for audio and video providing a standard buffer with GPU path
version: 0.4.5
publish_to: none
repository: https://github.com/PracticalXR/miniAV/tree/master/miniav

environment:
  sdk: ^3.9.0-21.0.dev

dependencies:
  miniav_platform_interface:
    path: ../miniav_platform_interface

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15

  platforms:
  windows:
  android:
  linux:
  ios:
  macos:
  web:
