/// Minimal hand-rolled FFI bindings for libavutil + libavcodec (+ a few
/// libavformat helpers).
///
/// **ABI pin**: this binding targets FFmpeg 8.x (libavutil 60, libavcodec 62,
/// libavformat 62) as shipped by the BtbN auto-downloader. `AVFrame` and
/// `AVPacket` struct layouts mirror those headers. If the loader picks up an
/// older shared library, only function symbols are guaranteed compatible —
/// the partial struct layouts here may misread pts/dts/etc.
///
/// We intentionally avoid mirroring `AVCodecContext`. All context configuration
/// goes through `av_opt_set_*` (string/int/q variants), which is ABI stable
/// across major FFmpeg versions.
// ignore_for_file: library_private_types_in_public_api
library;

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import 'ffmpeg_bindings.dart' as loader;

// =============================================================================
// Constants
// =============================================================================

/// Common AVERROR codes (negative POSIX errno values, generated by AVERROR()).
const int kAvErrorEAgain = -11; // -EAGAIN on Linux/Win
const int kAvErrorEof = -541478725; // -('E'<<24|'O'<<16|'F'<<8|' ')

/// AVPixelFormat values used in this MVP.
abstract final class AVPixelFormat {
  static const int yuv420p = 0;
  static const int yuyv422 = 1;
  static const int rgb24 = 2;
  static const int bgr24 = 3;
  static const int yuv422p = 4;
  static const int yuv444p = 5;
  static const int nv12 = 23;
  static const int nv21 = 24;
  static const int bgra = 28;
  static const int rgba = 26;
  static const int gray8 = 8;
}

/// AVCodecID values used in this MVP.
abstract final class AVCodecId {
  static const int none = 0;
  static const int h264 = 27;
  static const int hevc = 173;
  static const int mjpeg = 7;
  static const int vp8 = 139;
  static const int vp9 = 167;
  static const int av1 = 226;
  static const int mpeg4 = 12;
}

/// Flags for AVCodecContext (set via av_opt_set_int "flags").
const int kCodecFlagGlobalHeader = 1 << 22;

/// AVPacket flags.
const int kPktFlagKey = 0x0001;

/// AVFMT_GLOBALHEADER flag (libavformat).
const int kFmtGlobalHeader = 0x0040;

// =============================================================================
// Opaque types
// =============================================================================

final class AVCodec extends Opaque {}

final class AVCodecContext extends Opaque {}

/// `AVRational { int num; int den; }` — passed BY VALUE in libavutil APIs
/// such as `av_opt_set_q`. Dart FFI marshals this as a single 8-byte
/// aggregate, matching the C ABI on all our supported platforms.
final class AVRational extends Struct {
  @Int32()
  external int num;
  @Int32()
  external int den;
}

final class AVDictionary extends Opaque {}

final class AVFormatContext extends Opaque {}

final class AVOutputFormat extends Opaque {}

final class AVIOContext extends Opaque {}

/// Partial AVFormatContext layout — FFmpeg 8.x.
/// Only the prefix up to `pb` (the AVIOContext pointer) is mapped, which is
/// enough to wire an output file we opened ourselves via `avio_open`.
final class AVFormatContextPrefix extends Struct {
  external Pointer<Void> avClass; // const AVClass*
  external Pointer<Void> iformat; // const AVInputFormat*
  external Pointer<Void> oformat; // const AVOutputFormat*
  external Pointer<Void> privData;
  external Pointer<AVIOContext> pb;
}

/// `AVCodecParameters` partial layout — FFmpeg 8.x (libavcodec 62).
/// Only the prefix we care about for muxing video streams. The struct is
/// allocated by `avcodec_parameters_alloc()` so we never compute its size.
final class AVCodecParameters extends Struct {
  @Int32() // enum AVMediaType
  external int codecType;
  @Int32() // enum AVCodecID
  external int codecId;
  @Uint32()
  external int codecTag;
  external Pointer<Uint8> extradata;
  @Int32()
  external int extradataSize;
  external Pointer<Void> codedSideData;
  @Int32()
  external int nbCodedSideData;
  @Int32()
  external int format;
  @Int64()
  external int bitRate;
  @Int32()
  external int bitsPerCodedSample;
  @Int32()
  external int bitsPerRawSample;
  @Int32()
  external int profile;
  @Int32()
  external int level;
  @Int32()
  external int width;
  @Int32()
  external int height;
  // AVRational sample_aspect_ratio
  @Int32()
  external int sarNum;
  @Int32()
  external int sarDen;
  // AVRational framerate
  @Int32()
  external int frNum;
  @Int32()
  external int frDen;
}

/// `AVStream` partial prefix — FFmpeg 8.x (libavformat 62).
/// Allocated by `avformat_new_stream()`. We only read/write the first few
/// fields (index, codecpar pointer, time_base).
final class AVStream extends Struct {
  external Pointer<Void> avClass; // AVClass*
  @Int32()
  external int index;
  @Int32()
  external int id;
  external Pointer<AVCodecParameters> codecpar;
  external Pointer<Void> privData;
  // AVRational time_base
  @Int32()
  external int timeBaseNum;
  @Int32()
  external int timeBaseDen;
}

final class SwsContext extends Opaque {}

// =============================================================================
// AVFrame partial layout — FFmpeg 8.x (libavutil 60)
//
// Only the prefix up to `pts` is mapped. `av_frame_alloc()` returns a fully-
// allocated frame so we never compute sizeof() ourselves.
// =============================================================================

final class AVFrame extends Struct {
  external Pointer<Uint8> data0;
  external Pointer<Uint8> data1;
  external Pointer<Uint8> data2;
  external Pointer<Uint8> data3;
  external Pointer<Uint8> data4;
  external Pointer<Uint8> data5;
  external Pointer<Uint8> data6;
  external Pointer<Uint8> data7;

  @Int32()
  external int linesize0;
  @Int32()
  external int linesize1;
  @Int32()
  external int linesize2;
  @Int32()
  external int linesize3;
  @Int32()
  external int linesize4;
  @Int32()
  external int linesize5;
  @Int32()
  external int linesize6;
  @Int32()
  external int linesize7;

  external Pointer<Pointer<Uint8>> extendedData;

  @Int32()
  external int width;
  @Int32()
  external int height;
  @Int32()
  external int nbSamples;
  @Int32()
  external int format;
  @Int32()
  external int pictType;
  @Int32()
  external int sarNum;
  @Int32()
  external int sarDen;

  // 8-byte aligned (Dart FFI inserts padding automatically).
  @Int64()
  external int pts;
  @Int64()
  external int pktDts;
}

// =============================================================================
// AVPacket partial layout — FFmpeg 8.x (libavcodec 62)
// =============================================================================

final class AVPacket extends Struct {
  external Pointer<Void> buf; // AVBufferRef*
  @Int64()
  external int pts;
  @Int64()
  external int dts;
  external Pointer<Uint8> data;
  @Int32()
  external int size;
  @Int32()
  external int streamIndex;
  @Int32()
  external int flags;
  external Pointer<Void> sideData;
  @Int32()
  external int sideDataElems;
  @Int64()
  external int duration;
  @Int64()
  external int pos;
  external Pointer<Void> opaque;
  external Pointer<Void> opaqueRef;
  // AVRational time_base { num, den }
  @Int32()
  external int timeBaseNum;
  @Int32()
  external int timeBaseDen;
}

// =============================================================================
// Function typedefs
// =============================================================================

typedef _AvFrameAllocC = Pointer<AVFrame> Function();
typedef _AvFrameAlloc = Pointer<AVFrame> Function();

typedef _AvFrameFreeC = Void Function(Pointer<Pointer<AVFrame>>);
typedef _AvFrameFree = void Function(Pointer<Pointer<AVFrame>>);

typedef _AvFrameGetBufferC = Int32 Function(Pointer<AVFrame>, Int32 align);
typedef _AvFrameGetBuffer = int Function(Pointer<AVFrame>, int align);

typedef _AvFrameMakeWritableC = Int32 Function(Pointer<AVFrame>);
typedef _AvFrameMakeWritable = int Function(Pointer<AVFrame>);

typedef _AvFrameUnrefC = Void Function(Pointer<AVFrame>);
typedef _AvFrameUnref = void Function(Pointer<AVFrame>);

typedef _AvGetPixFmtC = Int32 Function(Pointer<Utf8>);
typedef _AvGetPixFmt = int Function(Pointer<Utf8>);

typedef _AvPacketAllocC = Pointer<AVPacket> Function();
typedef _AvPacketAlloc = Pointer<AVPacket> Function();

typedef _AvPacketFreeC = Void Function(Pointer<Pointer<AVPacket>>);
typedef _AvPacketFree = void Function(Pointer<Pointer<AVPacket>>);

typedef _AvPacketUnrefC = Void Function(Pointer<AVPacket>);
typedef _AvPacketUnref = void Function(Pointer<AVPacket>);

typedef _AvFindEncoderC = Pointer<AVCodec> Function(Pointer<Utf8>);
typedef _AvFindEncoder = Pointer<AVCodec> Function(Pointer<Utf8>);

typedef _AvFindEncoderByIdC = Pointer<AVCodec> Function(Int32);
typedef _AvFindEncoderById = Pointer<AVCodec> Function(int);

typedef _AvFindDecoderByIdC = Pointer<AVCodec> Function(Int32);
typedef _AvFindDecoderById = Pointer<AVCodec> Function(int);

typedef _AvCodecAllocCtxC = Pointer<AVCodecContext> Function(Pointer<AVCodec>);
typedef _AvCodecAllocCtx = Pointer<AVCodecContext> Function(Pointer<AVCodec>);

typedef _AvCodecFreeCtxC = Void Function(Pointer<Pointer<AVCodecContext>>);
typedef _AvCodecFreeCtx = void Function(Pointer<Pointer<AVCodecContext>>);

typedef _AvCodecOpen2C =
    Int32 Function(
      Pointer<AVCodecContext>,
      Pointer<AVCodec>,
      Pointer<Pointer<AVDictionary>>,
    );
typedef _AvCodecOpen2 =
    int Function(
      Pointer<AVCodecContext>,
      Pointer<AVCodec>,
      Pointer<Pointer<AVDictionary>>,
    );

typedef _AvSendFrameC =
    Int32 Function(Pointer<AVCodecContext>, Pointer<AVFrame>);
typedef _AvSendFrame = int Function(Pointer<AVCodecContext>, Pointer<AVFrame>);

typedef _AvReceivePacketC =
    Int32 Function(Pointer<AVCodecContext>, Pointer<AVPacket>);
typedef _AvReceivePacket =
    int Function(Pointer<AVCodecContext>, Pointer<AVPacket>);

typedef _AvSendPacketC =
    Int32 Function(Pointer<AVCodecContext>, Pointer<AVPacket>);
typedef _AvSendPacket =
    int Function(Pointer<AVCodecContext>, Pointer<AVPacket>);

typedef _AvReceiveFrameC =
    Int32 Function(Pointer<AVCodecContext>, Pointer<AVFrame>);
typedef _AvReceiveFrame =
    int Function(Pointer<AVCodecContext>, Pointer<AVFrame>);

typedef _AvDictSetC =
    Int32 Function(
      Pointer<Pointer<AVDictionary>>,
      Pointer<Utf8>,
      Pointer<Utf8>,
      Int32,
    );
typedef _AvDictSet =
    int Function(
      Pointer<Pointer<AVDictionary>>,
      Pointer<Utf8>,
      Pointer<Utf8>,
      int,
    );

typedef _AvDictFreeC = Void Function(Pointer<Pointer<AVDictionary>>);
typedef _AvDictFree = void Function(Pointer<Pointer<AVDictionary>>);

typedef _AvOptSetIntC =
    Int32 Function(Pointer<Void>, Pointer<Utf8>, Int64, Int32);
typedef _AvOptSetInt = int Function(Pointer<Void>, Pointer<Utf8>, int, int);

typedef _AvOptSetC =
    Int32 Function(Pointer<Void>, Pointer<Utf8>, Pointer<Utf8>, Int32);
typedef _AvOptSet =
    int Function(Pointer<Void>, Pointer<Utf8>, Pointer<Utf8>, int);

typedef _AvOptSetQC =
    Int32 Function(Pointer<Void>, Pointer<Utf8>, AVRational, Int32);
typedef _AvOptSetQ =
    int Function(Pointer<Void>, Pointer<Utf8>, AVRational, int);

typedef _AvOptSetPixelFmtC =
    Int32 Function(Pointer<Void>, Pointer<Utf8>, Int32, Int32);
typedef _AvOptSetPixelFmt =
    int Function(Pointer<Void>, Pointer<Utf8>, int, int);

typedef _AvStrErrorC = Int32 Function(Int32, Pointer<Utf8>, IntPtr);
typedef _AvStrError = int Function(int, Pointer<Utf8>, int);

typedef _AvImageGetBufferSizeC =
    Int32 Function(Int32 fmt, Int32 w, Int32 h, Int32 align);
typedef _AvImageGetBufferSize = int Function(int fmt, int w, int h, int align);

typedef _AvImageFillArraysC =
    Int32 Function(
      Pointer<Pointer<Uint8>> dstData, // uint8_t* dst_data[4]
      Pointer<Int32> dstLinesize, // int dst_linesize[4]
      Pointer<Uint8> src,
      Int32 fmt,
      Int32 w,
      Int32 h,
      Int32 align,
    );
typedef _AvImageFillArrays =
    int Function(
      Pointer<Pointer<Uint8>>,
      Pointer<Int32>,
      Pointer<Uint8>,
      int,
      int,
      int,
      int,
    );

// libavcodec helpers for AVCodecContext field access (ABI-stable accessors).
// Reserved for future use; currently we configure everything via av_opt_set.
// ignore: unused_element
typedef _AvccSetC = Void Function(Pointer<AVCodecContext> ctx, Int32 value);
// ignore: unused_element
typedef _AvccGetC = Int32 Function(Pointer<AVCodecContext> ctx);

// AVCodecParameters helpers (libavcodec).
typedef _AvCodecParametersAllocC = Pointer<AVCodecParameters> Function();
typedef _AvCodecParametersAlloc = Pointer<AVCodecParameters> Function();

typedef _AvCodecParametersFreeC =
    Void Function(Pointer<Pointer<AVCodecParameters>>);
typedef _AvCodecParametersFree =
    void Function(Pointer<Pointer<AVCodecParameters>>);

typedef _AvCodecParametersFromContextC =
    Int32 Function(Pointer<AVCodecParameters>, Pointer<AVCodecContext>);
typedef _AvCodecParametersFromContext =
    int Function(Pointer<AVCodecParameters>, Pointer<AVCodecContext>);

typedef _AvCodecParametersCopyC =
    Int32 Function(Pointer<AVCodecParameters>, Pointer<AVCodecParameters>);
typedef _AvCodecParametersCopy =
    int Function(Pointer<AVCodecParameters>, Pointer<AVCodecParameters>);

// libavformat function typedefs.
typedef _AvformatAllocOutputContext2C =
    Int32 Function(
      Pointer<Pointer<AVFormatContext>>,
      Pointer<AVOutputFormat>,
      Pointer<Utf8>,
      Pointer<Utf8>,
    );
typedef _AvformatAllocOutputContext2 =
    int Function(
      Pointer<Pointer<AVFormatContext>>,
      Pointer<AVOutputFormat>,
      Pointer<Utf8>,
      Pointer<Utf8>,
    );

typedef _AvformatNewStreamC =
    Pointer<AVStream> Function(Pointer<AVFormatContext>, Pointer<AVCodec>);
typedef _AvformatNewStream =
    Pointer<AVStream> Function(Pointer<AVFormatContext>, Pointer<AVCodec>);

typedef _AvioOpenC =
    Int32 Function(Pointer<Pointer<AVIOContext>>, Pointer<Utf8>, Int32);
typedef _AvioOpen =
    int Function(Pointer<Pointer<AVIOContext>>, Pointer<Utf8>, int);

typedef _AvioClosepC = Int32 Function(Pointer<Pointer<AVIOContext>>);
typedef _AvioClosep = int Function(Pointer<Pointer<AVIOContext>>);

typedef _AvformatWriteHeaderC =
    Int32 Function(Pointer<AVFormatContext>, Pointer<Pointer<AVDictionary>>);
typedef _AvformatWriteHeader =
    int Function(Pointer<AVFormatContext>, Pointer<Pointer<AVDictionary>>);

typedef _AvWriteTrailerC = Int32 Function(Pointer<AVFormatContext>);
typedef _AvWriteTrailer = int Function(Pointer<AVFormatContext>);

typedef _AvInterleavedWriteFrameC =
    Int32 Function(Pointer<AVFormatContext>, Pointer<AVPacket>);
typedef _AvInterleavedWriteFrame =
    int Function(Pointer<AVFormatContext>, Pointer<AVPacket>);

typedef _AvformatFreeContextC = Void Function(Pointer<AVFormatContext>);
typedef _AvformatFreeContext = void Function(Pointer<AVFormatContext>);

// AVIO_FLAG_WRITE = 2.
const int kAvioFlagWrite = 2;

// HW device / frame management ------------------------------------------------
//
// AVBufferRef* is opaque to us — we treat it as Pointer<Void> and only ever
// hand it back to FFmpeg or the shim.

typedef _AvHwdeviceCtxAllocC = Pointer<Void> Function(Int32 type);
typedef _AvHwdeviceCtxAlloc = Pointer<Void> Function(int type);

typedef _AvHwdeviceCtxInitC = Int32 Function(Pointer<Void> ref);
typedef _AvHwdeviceCtxInit = int Function(Pointer<Void> ref);

typedef _AvHwdeviceCtxCreateC =
    Int32 Function(
      Pointer<Pointer<Void>> outRef,
      Int32 type,
      Pointer<Utf8> device,
      Pointer<Void> opts,
      Int32 flags,
    );
typedef _AvHwdeviceCtxCreate =
    int Function(
      Pointer<Pointer<Void>> outRef,
      int type,
      Pointer<Utf8> device,
      Pointer<Void> opts,
      int flags,
    );

typedef _AvHwframeCtxAllocC = Pointer<Void> Function(Pointer<Void> deviceCtx);
typedef _AvHwframeCtxAlloc = Pointer<Void> Function(Pointer<Void> deviceCtx);

typedef _AvHwframeCtxInitC = Int32 Function(Pointer<Void> ref);
typedef _AvHwframeCtxInit = int Function(Pointer<Void> ref);

typedef _AvHwframeGetBufferC =
    Int32 Function(
      Pointer<Void> hwframesRef,
      Pointer<AVFrame> frame,
      Int32 flags,
    );
typedef _AvHwframeGetBuffer =
    int Function(Pointer<Void> hwframesRef, Pointer<AVFrame> frame, int flags);

typedef _AvBufferRefC = Pointer<Void> Function(Pointer<Void> ref);
typedef _AvBufferRef = Pointer<Void> Function(Pointer<Void> ref);

typedef _AvBufferUnrefC = Void Function(Pointer<Pointer<Void>> refp);
typedef _AvBufferUnref = void Function(Pointer<Pointer<Void>> refp);

typedef _AvHwdeviceFindTypeByNameC = Int32 Function(Pointer<Utf8> name);
typedef _AvHwdeviceFindTypeByName = int Function(Pointer<Utf8> name);

// AVHWDeviceType enum (FFmpeg n7/n8 stable subset).
const int kAvHwdeviceTypeNone = 0;
const int kAvHwdeviceTypeVdpau = 1;
const int kAvHwdeviceTypeCuda = 2;
const int kAvHwdeviceTypeVaapi = 3;
const int kAvHwdeviceTypeDxva2 = 4;
const int kAvHwdeviceTypeQsv = 5;
const int kAvHwdeviceTypeVideoToolbox = 6;
const int kAvHwdeviceTypeD3d11Va = 7;
const int kAvHwdeviceTypeDrm = 8;
const int kAvHwdeviceTypeOpenCl = 9;
const int kAvHwdeviceTypeMediaCodec = 10;
const int kAvHwdeviceTypeVulkan = 11;
const int kAvHwdeviceTypeD3d12Va = 12;

// =============================================================================
// Bindings holder
// =============================================================================

class Ffmpeg {
  Ffmpeg._(this._avutil, this._avcodec, this._avformat);

  final DynamicLibrary _avutil;
  final DynamicLibrary _avcodec;
  final DynamicLibrary? _avformat;

  // Frame
  late final _AvFrameAlloc avFrameAlloc = _avutil
      .lookupFunction<_AvFrameAllocC, _AvFrameAlloc>('av_frame_alloc');
  late final _AvFrameFree avFrameFree = _avutil
      .lookupFunction<_AvFrameFreeC, _AvFrameFree>('av_frame_free');
  late final _AvFrameGetBuffer avFrameGetBuffer = _avutil
      .lookupFunction<_AvFrameGetBufferC, _AvFrameGetBuffer>(
        'av_frame_get_buffer',
      );
  late final _AvFrameMakeWritable avFrameMakeWritable = _avutil
      .lookupFunction<_AvFrameMakeWritableC, _AvFrameMakeWritable>(
        'av_frame_make_writable',
      );

  late final _AvFrameUnref avFrameUnref = _avutil
      .lookupFunction<_AvFrameUnrefC, _AvFrameUnref>('av_frame_unref');

  /// Resolve a pixel-format name (e.g. "rgb0", "nv12", "yuv420p") to its
  /// [AVPixelFormat] enum value. Returns -1 on unknown name.
  late final _AvGetPixFmt avGetPixFmtByName = _avutil
      .lookupFunction<_AvGetPixFmtC, _AvGetPixFmt>('av_get_pix_fmt');

  // HW device / frame management (libavutil)
  late final _AvHwdeviceCtxAlloc avHwdeviceCtxAlloc = _avutil
      .lookupFunction<_AvHwdeviceCtxAllocC, _AvHwdeviceCtxAlloc>(
        'av_hwdevice_ctx_alloc',
      );
  late final _AvHwdeviceCtxInit avHwdeviceCtxInit = _avutil
      .lookupFunction<_AvHwdeviceCtxInitC, _AvHwdeviceCtxInit>(
        'av_hwdevice_ctx_init',
      );
  late final _AvHwdeviceCtxCreate avHwdeviceCtxCreate = _avutil
      .lookupFunction<_AvHwdeviceCtxCreateC, _AvHwdeviceCtxCreate>(
        'av_hwdevice_ctx_create',
      );
  late final _AvHwframeCtxAlloc avHwframeCtxAlloc = _avutil
      .lookupFunction<_AvHwframeCtxAllocC, _AvHwframeCtxAlloc>(
        'av_hwframe_ctx_alloc',
      );
  late final _AvHwframeCtxInit avHwframeCtxInit = _avutil
      .lookupFunction<_AvHwframeCtxInitC, _AvHwframeCtxInit>(
        'av_hwframe_ctx_init',
      );
  late final _AvHwframeGetBuffer avHwframeGetBuffer = _avutil
      .lookupFunction<_AvHwframeGetBufferC, _AvHwframeGetBuffer>(
        'av_hwframe_get_buffer',
      );
  late final _AvBufferRef avBufferRef = _avutil
      .lookupFunction<_AvBufferRefC, _AvBufferRef>('av_buffer_ref');
  late final _AvBufferUnref avBufferUnref = _avutil
      .lookupFunction<_AvBufferUnrefC, _AvBufferUnref>('av_buffer_unref');
  late final _AvHwdeviceFindTypeByName avHwdeviceFindTypeByName = _avutil
      .lookupFunction<_AvHwdeviceFindTypeByNameC, _AvHwdeviceFindTypeByName>(
        'av_hwdevice_find_type_by_name',
      );

  // Packet
  late final _AvPacketAlloc avPacketAlloc = _avcodec
      .lookupFunction<_AvPacketAllocC, _AvPacketAlloc>('av_packet_alloc');
  late final _AvPacketFree avPacketFree = _avcodec
      .lookupFunction<_AvPacketFreeC, _AvPacketFree>('av_packet_free');
  late final _AvPacketUnref avPacketUnref = _avcodec
      .lookupFunction<_AvPacketUnrefC, _AvPacketUnref>('av_packet_unref');

  // Codec lookup
  late final _AvFindEncoder avcodecFindEncoderByName = _avcodec
      .lookupFunction<_AvFindEncoderC, _AvFindEncoder>(
        'avcodec_find_encoder_by_name',
      );
  late final _AvFindEncoderById avcodecFindEncoder = _avcodec
      .lookupFunction<_AvFindEncoderByIdC, _AvFindEncoderById>(
        'avcodec_find_encoder',
      );
  late final _AvFindDecoderById avcodecFindDecoder = _avcodec
      .lookupFunction<_AvFindDecoderByIdC, _AvFindDecoderById>(
        'avcodec_find_decoder',
      );

  // Context
  late final _AvCodecAllocCtx avcodecAllocContext3 = _avcodec
      .lookupFunction<_AvCodecAllocCtxC, _AvCodecAllocCtx>(
        'avcodec_alloc_context3',
      );
  late final _AvCodecFreeCtx avcodecFreeContext = _avcodec
      .lookupFunction<_AvCodecFreeCtxC, _AvCodecFreeCtx>(
        'avcodec_free_context',
      );
  late final _AvCodecOpen2 avcodecOpen2 = _avcodec
      .lookupFunction<_AvCodecOpen2C, _AvCodecOpen2>('avcodec_open2');

  // Encode
  late final _AvSendFrame avcodecSendFrame = _avcodec
      .lookupFunction<_AvSendFrameC, _AvSendFrame>('avcodec_send_frame');
  late final _AvReceivePacket avcodecReceivePacket = _avcodec
      .lookupFunction<_AvReceivePacketC, _AvReceivePacket>(
        'avcodec_receive_packet',
      );

  // Decode
  late final _AvSendPacket avcodecSendPacket = _avcodec
      .lookupFunction<_AvSendPacketC, _AvSendPacket>('avcodec_send_packet');
  late final _AvReceiveFrame avcodecReceiveFrame = _avcodec
      .lookupFunction<_AvReceiveFrameC, _AvReceiveFrame>(
        'avcodec_receive_frame',
      );

  // Dictionary (encoder options)
  late final _AvDictSet avDictSet = _avutil
      .lookupFunction<_AvDictSetC, _AvDictSet>('av_dict_set');
  late final _AvDictFree avDictFree = _avutil
      .lookupFunction<_AvDictFreeC, _AvDictFree>('av_dict_free');

  // AVOptions (preferred for context configuration)
  late final _AvOptSetInt avOptSetInt = _avutil
      .lookupFunction<_AvOptSetIntC, _AvOptSetInt>('av_opt_set_int');
  late final _AvOptSet avOptSet = _avutil.lookupFunction<_AvOptSetC, _AvOptSet>(
    'av_opt_set',
  );
  late final _AvOptSetQ avOptSetQ = _avutil
      .lookupFunction<_AvOptSetQC, _AvOptSetQ>('av_opt_set_q');
  late final _AvOptSetPixelFmt avOptSetPixelFmt = _avutil
      .lookupFunction<_AvOptSetPixelFmtC, _AvOptSetPixelFmt>(
        'av_opt_set_pixel_fmt',
      );

  // Errors
  late final _AvStrError avStrError = _avutil
      .lookupFunction<_AvStrErrorC, _AvStrError>('av_strerror');

  // Image helpers
  late final _AvImageGetBufferSize avImageGetBufferSize = _avutil
      .lookupFunction<_AvImageGetBufferSizeC, _AvImageGetBufferSize>(
        'av_image_get_buffer_size',
      );
  late final _AvImageFillArrays avImageFillArrays = _avutil
      .lookupFunction<_AvImageFillArraysC, _AvImageFillArrays>(
        'av_image_fill_arrays',
      );

  // AVCodecParameters helpers (libavcodec).
  late final _AvCodecParametersAlloc avcodecParametersAlloc = _avcodec
      .lookupFunction<_AvCodecParametersAllocC, _AvCodecParametersAlloc>(
        'avcodec_parameters_alloc',
      );
  late final _AvCodecParametersFree avcodecParametersFree = _avcodec
      .lookupFunction<_AvCodecParametersFreeC, _AvCodecParametersFree>(
        'avcodec_parameters_free',
      );
  late final _AvCodecParametersFromContext avcodecParametersFromContext =
      _avcodec.lookupFunction<
        _AvCodecParametersFromContextC,
        _AvCodecParametersFromContext
      >('avcodec_parameters_from_context');
  late final _AvCodecParametersCopy avcodecParametersCopy = _avcodec
      .lookupFunction<_AvCodecParametersCopyC, _AvCodecParametersCopy>(
        'avcodec_parameters_copy',
      );

  // libavformat (lazy — only present if loader.avformat resolved).
  bool get hasAvformat => _avformat != null;
  DynamicLibrary get _fmt {
    final lib = _avformat;
    if (lib == null) {
      throw StateError('libavformat not loaded');
    }
    return lib;
  }

  late final _AvformatAllocOutputContext2 avformatAllocOutputContext2 = _fmt
      .lookupFunction<
        _AvformatAllocOutputContext2C,
        _AvformatAllocOutputContext2
      >('avformat_alloc_output_context2');
  late final _AvformatNewStream avformatNewStream = _fmt
      .lookupFunction<_AvformatNewStreamC, _AvformatNewStream>(
        'avformat_new_stream',
      );
  late final _AvioOpen avioOpen = _fmt.lookupFunction<_AvioOpenC, _AvioOpen>(
    'avio_open',
  );
  late final _AvioClosep avioClosep = _fmt
      .lookupFunction<_AvioClosepC, _AvioClosep>('avio_closep');
  late final _AvformatWriteHeader avformatWriteHeader = _fmt
      .lookupFunction<_AvformatWriteHeaderC, _AvformatWriteHeader>(
        'avformat_write_header',
      );
  late final _AvWriteTrailer avWriteTrailer = _fmt
      .lookupFunction<_AvWriteTrailerC, _AvWriteTrailer>('av_write_trailer');
  late final _AvInterleavedWriteFrame avInterleavedWriteFrame = _fmt
      .lookupFunction<_AvInterleavedWriteFrameC, _AvInterleavedWriteFrame>(
        'av_interleaved_write_frame',
      );
  late final _AvformatFreeContext avformatFreeContext = _fmt
      .lookupFunction<_AvformatFreeContextC, _AvformatFreeContext>(
        'avformat_free_context',
      );

  /// Wrap an AVERROR code into a Dart exception string.
  String strError(int err) {
    const bufLen = 256;
    final buf = calloc<Uint8>(bufLen).cast<Utf8>();
    try {
      avStrError(err, buf, bufLen);
      return buf.toDartString();
    } finally {
      calloc.free(buf);
    }
  }

  // ---------------------------------------------------------------------------
  // Singleton
  // ---------------------------------------------------------------------------

  static Ffmpeg? _instance;

  /// Returns the cached instance, or null if FFmpeg has not been loaded.
  ///
  /// Call [loader.tryLoadFFmpeg] or [loader.ensureFFmpegLoaded] first.
  static Ffmpeg? instance() {
    if (_instance != null) return _instance;
    final avutil = loader.avutil;
    final avcodec = loader.avcodec;
    if (avutil == null || avcodec == null) return null;
    return _instance = Ffmpeg._(avutil, avcodec, loader.avformat);
  }

  /// Test hook: drop the cached singleton (forces a re-bind on the next call).
  static void resetForTests() => _instance = null;
}
