name: miniav_platform_interface
description: A platform interface for the miniav library, allowing for different implementations.
version: 0.4.5
publish_to: none
repository: https://github.com/PracticalXR/miniAV/tree/master/miniav_platform_interface

environment:
  sdk: ^3.9.0-21.0.dev

dependencies:
  miniav_ffi:
    path: ../miniav_ffi
  miniav_web:
    path: ../miniav_web

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
